### ISSUE TITLE
Remove usage of text from buttons in pause menu [2-6h]

### ISSUE THREAD

**Issue by nya-elimu** [elimu-ai/VoltAir#61]
Make it possible for a child who cannot read words to navigate the pause menu.

Remove the option "Main menu".

Replace "Change level" an icon/image representing the level selection menu.

**Comment by nya-elimu** [comment]
![screenshot_20170618-163729](https://user-images.githubusercontent.com/15718174/27261142-08650e0a-543d-11e7-8560-7a731712b6d0.png)

**Comment by diegowald** [comment]
HI @jogrimst , could you please give me some advice on images?

I am using play for resume, three horizontal lines for main menu (the same as top left button when playing), and powerOn/Off for quit. I have no idea on what to use for change level.

I will push my changes, please don't merge it yet, since I need to do some work on sizing.
